### ISSUE TITLE
Correct way to add headers

### ISSUE THREAD

**Issue by Slemgrim** [php-fig/http-factory#4]
PSR-7 has the handy ->getHeaderLine and ->getHeader methods. 
The spec for PSR-17 doesn't really mention headers. 

Would a implementation of  ServerRequestFactoryInterface::createServerRequestFromArray($_SERVER) add all the sent headers to the request or is this out of the scope of this PSR?

**Comment by shadowhand** [comment]
@Slemgrim we chose not to address that because typically the ServerRequest implementation is known during bootstrapping and will offer a method like:

```php
$request = \Zend\Diactoros\ServerRequestFactory::createFromGlobals();
```

There is also [nyholm/psr7-server](https://packagist.org/packages/nyholm/psr7-server) which uses PSR-17 factories to accomplish the same thing. This package *might* be adopted by FIG in the future.

**Comment by Slemgrim** [comment]
@shadowhand thank you for the fast reply. 
I'm happy with the nyholm/psr7-server implementation. This can be closed.
